-- MySQL schema for SignFriend progress board and notifications
-- Run with: mysql -u <user> -p < db/mysql_schema.sql

CREATE DATABASE IF NOT EXISTS signfriend CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE signfriend;

-- Users (simplified; integrate with your auth system later)
CREATE TABLE IF NOT EXISTS users (
  id            BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  email         VARCHAR(190) NOT NULL UNIQUE,
  display_name  VARCHAR(120) NOT NULL,
  avatar_url    VARCHAR(300) NULL,
  created_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- Lessons catalog (optional minimal)
CREATE TABLE IF NOT EXISTS lessons (
  id            BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  title         VARCHAR(120) NOT NULL,
  category      VARCHAR(80) NULL,
  created_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- Progress entries generated by the board (practice/completions)
CREATE TABLE IF NOT EXISTS progress_entries (
  id            BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id       BIGINT UNSIGNED NOT NULL,
  lesson_id     BIGINT UNSIGNED NULL,
  type          ENUM('practice','quiz','streak','achievement') NOT NULL,
  value_num     INT NULL,               -- e.g., accuracy, minutes, streak days
  value_text    VARCHAR(255) NULL,      -- e.g., label detected, achievement name
  metadata      JSON NULL,
  created_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_progress_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_progress_lesson FOREIGN KEY (lesson_id) REFERENCES lessons(id) ON DELETE SET NULL,
  INDEX idx_progress_user_created (user_id, created_at)
) ENGINE=InnoDB;

-- Notifications generated from progress rules
CREATE TABLE IF NOT EXISTS notifications (
  id            BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id       BIGINT UNSIGNED NOT NULL,
  type          ENUM('progress','achievement','reminder','system') NOT NULL,
  title         VARCHAR(160) NOT NULL,
  message       VARCHAR(500) NOT NULL,
  read_flag     TINYINT(1) NOT NULL DEFAULT 0,
  metadata      JSON NULL,
  created_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_notifications_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  INDEX idx_notifications_user_read (user_id, read_flag, created_at)
) ENGINE=InnoDB;

-- Example seed data
INSERT INTO users (email, display_name) VALUES 
  ('usuario@example.com','usuario')
ON DUPLICATE KEY UPDATE display_name=VALUES(display_name);

INSERT INTO lessons (title, category) VALUES
  ('Hola','Saludos'), ('Gracias','Saludos')
ON DUPLICATE KEY UPDATE category=VALUES(category);

-- Example progress and notifications for the seed user (id=1)
INSERT INTO progress_entries (user_id, lesson_id, type, value_num, value_text, metadata)
VALUES (1, 1, 'practice', 80, 'hola', JSON_OBJECT('accuracy',80));

INSERT INTO notifications (user_id, type, title, message, metadata)
VALUES 
(1, 'progress', 'Progreso de práctica', 'Completaste 3 prácticas hoy. ¡Sigue así! 🎉', JSON_OBJECT('completedPractices',3)),
(1, 'achievement', 'Racha activa', 'Alcanzaste una racha de 5 días.', JSON_OBJECT('streakDays',5));
